---
driver:
  name: vagrant

provisioner:
  name: dsc
  dsc_local_configuration_manager_version: wmf5  
  modules_path: .
  configuration_script_folder: Examples
  configuration_script: TextFile_Example.ps1
  configuration_data_variable: configData
  configuration_name: TextFile  

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests

platforms:
  - name: windows_nano
    driver:
      box: mwrock/WindowsNanoDSC

suites:
  - name: TextFile